services:
  backend:
    command: fastapi dev app/main.py --host 0.0.0.0
    volumes:
      - ./backend/app:/app/backend/app
      - ./backend/scripts:/app/backend/scripts
      - ./backend/alembic.ini:/app/backend/alembic.ini

  frontend:
    build:
      target: development
    environment:
      NPM_CONFIG_REGISTRY: https://registry.npmjs.org/
      VITE_GLOB_API_URL: http://localhost:8000/api/v1
    command: pnpm -F @vben/web-antd run dev --host 0.0.0.0
    volumes:
      - ./frontend/apps/web-antd/src:/app/apps/web-antd/src
      - frontend-node-modules:/app/node_modules
    ports:
      - "5174:5173"

volumes:
  frontend-node-modules:
