services:
  db:
    image: postgres:17
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?Variable not set}
      POSTGRES_USER: ${POSTGRES_USER?Variable not set}
      POSTGRES_DB: ${POSTGRES_DB?Variable not set}
    ports:
      - "5432:5432"

  mailcatcher:
    image: axllent/mailpit:latest
    restart: unless-stopped
    ports:
      - "1080:8025"
      - "1025:1025"

  adminer:
    image: adminer:latest
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

  prestart:
    build:
      context: .
      dockerfile: backend/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    command: bash scripts/prestart.sh
    env_file:
      - .env
    environment:
      POSTGRES_SERVER: db

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      prestart:
        condition: service_completed_successfully
    env_file:
      - .env
    environment:
      POSTGRES_SERVER: db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/utils/health-check"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        VITE_GLOB_API_URL: http://localhost:8000/api/v1
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "5173:80"

volumes:
  app-db-data:
