"""add optional workflow module

Revision ID: 1cb1a9218afe
Revises: b8c9d1e2f3a4
Create Date: 2026-07-15 11:28:12.721806

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1cb1a9218afe'
down_revision = 'b8c9d1e2f3a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflowdefinition',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_workflowdefinition_id_tenant_id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_workflowdefinition_tenant_code')
    )
    op.create_index(op.f('ix_workflowdefinition_code'), 'workflowdefinition', ['code'], unique=False)
    op.create_index(op.f('ix_workflowdefinition_tenant_id'), 'workflowdefinition', ['tenant_id'], unique=False)
    op.create_table('workflowdefinitionversion',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('definition_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('process_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('bpmn_xml', sa.Text(), nullable=False),
    sa.Column('task_assignments', sa.JSON(), nullable=False),
    sa.Column('timeout_hours', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['definition_id', 'tenant_id'], ['workflowdefinition.id', 'workflowdefinition.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('definition_id', 'version', name='uq_workflowdefinitionversion_number'),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_workflowdefinitionversion_id_tenant_id')
    )
    op.create_index(op.f('ix_workflowdefinitionversion_definition_id'), 'workflowdefinitionversion', ['definition_id'], unique=False)
    op.create_index(op.f('ix_workflowdefinitionversion_tenant_id'), 'workflowdefinitionversion', ['tenant_id'], unique=False)
    op.create_table('workflowinstance',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('definition_version_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('business_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('business_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('form_data', sa.JSON(), nullable=False),
    sa.Column('engine_state', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['definition_version_id', 'tenant_id'], ['workflowdefinitionversion.id', 'workflowdefinitionversion.tenant_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['started_by'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_workflowinstance_id_tenant_id')
    )
    op.create_index(op.f('ix_workflowinstance_definition_version_id'), 'workflowinstance', ['definition_version_id'], unique=False)
    op.create_index(op.f('ix_workflowinstance_tenant_id'), 'workflowinstance', ['tenant_id'], unique=False)
    op.create_table('workflowtask',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('instance_id', sa.Uuid(), nullable=False),
    sa.Column('engine_task_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('task_key', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('assignment_expression', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['completed_by'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['instance_id', 'tenant_id'], ['workflowinstance.id', 'workflowinstance.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_workflowtask_id_tenant_id'),
    sa.UniqueConstraint('tenant_id', 'engine_task_id', name='uq_workflowtask_tenant_engine_task')
    )
    op.create_index(op.f('ix_workflowtask_instance_id'), 'workflowtask', ['instance_id'], unique=False)
    op.create_index(op.f('ix_workflowtask_tenant_id'), 'workflowtask', ['tenant_id'], unique=False)
    op.create_table('workflowaudit',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('instance_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['instance_id', 'tenant_id'], ['workflowinstance.id', 'workflowinstance.tenant_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id', 'tenant_id'], ['workflowtask.id', 'workflowtask.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflowaudit_instance_id'), 'workflowaudit', ['instance_id'], unique=False)
    op.create_index(op.f('ix_workflowaudit_tenant_id'), 'workflowaudit', ['tenant_id'], unique=False)
    op.create_table('workflowcc',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('recipient_user_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recipient_user_id', 'tenant_id'], ['tenantmembership.user_id', 'tenantmembership.tenant_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id', 'tenant_id'], ['workflowtask.id', 'workflowtask.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'recipient_user_id', name='uq_workflowcc_task_recipient')
    )
    op.create_index(op.f('ix_workflowcc_recipient_user_id'), 'workflowcc', ['recipient_user_id'], unique=False)
    op.create_index(op.f('ix_workflowcc_task_id'), 'workflowcc', ['task_id'], unique=False)
    op.create_index(op.f('ix_workflowcc_tenant_id'), 'workflowcc', ['tenant_id'], unique=False)
    op.create_table('workflownotification',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('instance_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('recipient_user_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instance_id', 'tenant_id'], ['workflowinstance.id', 'workflowinstance.tenant_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_user_id', 'tenant_id'], ['tenantmembership.user_id', 'tenantmembership.tenant_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id', 'tenant_id'], ['workflowtask.id', 'workflowtask.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflownotification_instance_id'), 'workflownotification', ['instance_id'], unique=False)
    op.create_index(op.f('ix_workflownotification_recipient_user_id'), 'workflownotification', ['recipient_user_id'], unique=False)
    op.create_index(op.f('ix_workflownotification_tenant_id'), 'workflownotification', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflownotification_tenant_id'), table_name='workflownotification')
    op.drop_index(op.f('ix_workflownotification_recipient_user_id'), table_name='workflownotification')
    op.drop_index(op.f('ix_workflownotification_instance_id'), table_name='workflownotification')
    op.drop_table('workflownotification')
    op.drop_index(op.f('ix_workflowcc_tenant_id'), table_name='workflowcc')
    op.drop_index(op.f('ix_workflowcc_task_id'), table_name='workflowcc')
    op.drop_index(op.f('ix_workflowcc_recipient_user_id'), table_name='workflowcc')
    op.drop_table('workflowcc')
    op.drop_index(op.f('ix_workflowaudit_tenant_id'), table_name='workflowaudit')
    op.drop_index(op.f('ix_workflowaudit_instance_id'), table_name='workflowaudit')
    op.drop_table('workflowaudit')
    op.drop_index(op.f('ix_workflowtask_tenant_id'), table_name='workflowtask')
    op.drop_index(op.f('ix_workflowtask_instance_id'), table_name='workflowtask')
    op.drop_table('workflowtask')
    op.drop_index(op.f('ix_workflowinstance_tenant_id'), table_name='workflowinstance')
    op.drop_index(op.f('ix_workflowinstance_definition_version_id'), table_name='workflowinstance')
    op.drop_table('workflowinstance')
    op.drop_index(op.f('ix_workflowdefinitionversion_tenant_id'), table_name='workflowdefinitionversion')
    op.drop_index(op.f('ix_workflowdefinitionversion_definition_id'), table_name='workflowdefinitionversion')
    op.drop_table('workflowdefinitionversion')
    op.drop_index(op.f('ix_workflowdefinition_tenant_id'), table_name='workflowdefinition')
    op.drop_index(op.f('ix_workflowdefinition_code'), table_name='workflowdefinition')
    op.drop_table('workflowdefinition')
    # ### end Alembic commands ###
