"""add capability provider bindings

Revision ID: 44521cee7948
Revises: e631b07deab4
Create Date: 2026-07-20 01:07:40.480056

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '44521cee7948'
down_revision = 'e631b07deab4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capabilitybinding',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('consumer_module', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('aggregate_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('aggregate_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('capability_code', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('provider_code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('provider_version', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('external_instance_id', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'consumer_module', 'aggregate_type', 'aggregate_id', 'capability_code', name='uq_capability_binding_aggregate')
    )
    op.create_index(op.f('ix_capabilitybinding_consumer_module'), 'capabilitybinding', ['consumer_module'], unique=False)
    op.create_index(op.f('ix_capabilitybinding_status'), 'capabilitybinding', ['status'], unique=False)
    op.create_index(op.f('ix_capabilitybinding_tenant_id'), 'capabilitybinding', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_capabilitybinding_tenant_id'), table_name='capabilitybinding')
    op.drop_index(op.f('ix_capabilitybinding_status'), table_name='capabilitybinding')
    op.drop_index(op.f('ix_capabilitybinding_consumer_module'), table_name='capabilitybinding')
    op.drop_table('capabilitybinding')
    # ### end Alembic commands ###
