"""add lifecycle outbox and archival state

Revision ID: e631b07deab4
Revises: f4ad952a23c6
Create Date: 2026-07-20 00:32:16.017517

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e631b07deab4'
down_revision = 'f4ad952a23c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outboxevent',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('module_code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('event_version', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('aggregate_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('payload', sqlmodel.sql.sqltypes.AutoString(length=16000), nullable=False),
    sa.Column('trace_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dead_lettered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outboxevent_aggregate_id'), 'outboxevent', ['aggregate_id'], unique=False)
    op.create_index(op.f('ix_outboxevent_available_at'), 'outboxevent', ['available_at'], unique=False)
    op.create_index(op.f('ix_outboxevent_event_type'), 'outboxevent', ['event_type'], unique=False)
    op.create_index(op.f('ix_outboxevent_module_code'), 'outboxevent', ['module_code'], unique=False)
    op.create_index(op.f('ix_outboxevent_status'), 'outboxevent', ['status'], unique=False)
    op.create_index(op.f('ix_outboxevent_tenant_id'), 'outboxevent', ['tenant_id'], unique=False)
    op.create_table('eventconsumerreceipt',
    sa.Column('consumer_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['outboxevent.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('consumer_name', 'event_id')
    )
    op.add_column('department', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_department_archived_at'), 'department', ['archived_at'], unique=False)
    op.add_column('post', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_post_archived_at'), 'post', ['archived_at'], unique=False)
    op.add_column('user', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user', sa.Column('anonymized_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_user_anonymized_at'), 'user', ['anonymized_at'], unique=False)
    op.create_index(op.f('ix_user_archived_at'), 'user', ['archived_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_archived_at'), table_name='user')
    op.drop_index(op.f('ix_user_anonymized_at'), table_name='user')
    op.drop_column('user', 'anonymized_at')
    op.drop_column('user', 'archived_at')
    op.drop_index(op.f('ix_post_archived_at'), table_name='post')
    op.drop_column('post', 'archived_at')
    op.drop_index(op.f('ix_department_archived_at'), table_name='department')
    op.drop_column('department', 'archived_at')
    op.drop_table('eventconsumerreceipt')
    op.drop_index(op.f('ix_outboxevent_tenant_id'), table_name='outboxevent')
    op.drop_index(op.f('ix_outboxevent_status'), table_name='outboxevent')
    op.drop_index(op.f('ix_outboxevent_module_code'), table_name='outboxevent')
    op.drop_index(op.f('ix_outboxevent_event_type'), table_name='outboxevent')
    op.drop_index(op.f('ix_outboxevent_available_at'), table_name='outboxevent')
    op.drop_index(op.f('ix_outboxevent_aggregate_id'), table_name='outboxevent')
    op.drop_table('outboxevent')
    # ### end Alembic commands ###
