"""add module runtime access control

Revision ID: f4ad952a23c6
Revises: 5f6a7b8c9d0e
Create Date: 2026-07-20 00:26:29.165126

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f4ad952a23c6'
down_revision = '5f6a7b8c9d0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moduleregistry',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('desired_state', sa.String(length=32), nullable=False),
    sa.Column('observed_state', sa.String(length=32), nullable=False),
    sa.Column('manifest_digest', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('target_revision', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('actual_revision', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('health_details', sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_moduleregistry_desired_state'), 'moduleregistry', ['desired_state'], unique=False)
    op.create_index(op.f('ix_moduleregistry_observed_state'), 'moduleregistry', ['observed_state'], unique=False)
    op.create_table('tenantplanmodule',
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('module_code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['tenantplan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('plan_id', 'module_code')
    )
    op.create_table('modulestateaudit',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('module_code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('previous_value', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('next_value', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modulestateaudit_module_code'), 'modulestateaudit', ['module_code'], unique=False)
    op.create_index(op.f('ix_modulestateaudit_tenant_id'), 'modulestateaudit', ['tenant_id'], unique=False)
    op.create_table('tenantmodule',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('module_code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id', 'module_code')
    )
    op.create_table('tenantmoduleentitlementoverride',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('module_code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('effect', sa.String(length=32), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('operator_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['operator_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenantmoduleentitlementoverride_ends_at'), 'tenantmoduleentitlementoverride', ['ends_at'], unique=False)
    op.create_index(op.f('ix_tenantmoduleentitlementoverride_module_code'), 'tenantmoduleentitlementoverride', ['module_code'], unique=False)
    op.create_index(op.f('ix_tenantmoduleentitlementoverride_starts_at'), 'tenantmoduleentitlementoverride', ['starts_at'], unique=False)
    op.create_index(op.f('ix_tenantmoduleentitlementoverride_tenant_id'), 'tenantmoduleentitlementoverride', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenantmoduleentitlementoverride_tenant_id'), table_name='tenantmoduleentitlementoverride')
    op.drop_index(op.f('ix_tenantmoduleentitlementoverride_starts_at'), table_name='tenantmoduleentitlementoverride')
    op.drop_index(op.f('ix_tenantmoduleentitlementoverride_module_code'), table_name='tenantmoduleentitlementoverride')
    op.drop_index(op.f('ix_tenantmoduleentitlementoverride_ends_at'), table_name='tenantmoduleentitlementoverride')
    op.drop_table('tenantmoduleentitlementoverride')
    op.drop_table('tenantmodule')
    op.drop_index(op.f('ix_modulestateaudit_tenant_id'), table_name='modulestateaudit')
    op.drop_index(op.f('ix_modulestateaudit_module_code'), table_name='modulestateaudit')
    op.drop_table('modulestateaudit')
    op.drop_table('tenantplanmodule')
    op.drop_index(op.f('ix_moduleregistry_observed_state'), table_name='moduleregistry')
    op.drop_index(op.f('ix_moduleregistry_desired_state'), table_name='moduleregistry')
    op.drop_table('moduleregistry')
    # ### end Alembic commands ###
