from app.api.routes import (
    dashboard,
    departments,
    dictionaries,
    files,
    login,
    logs,
    mail,
    menus,
    modules,
    notices,
    oauth2,
    permissions,
    posts,
    roles,
    site_messages,
    sms,
    social,
    tenants,
    users,
    utils,
)
from app.api.routes import settings as system_settings
from app.modules.contracts import EventContract, MigrationSpec, ModuleDefinition

definition = ModuleDefinition(
    code="platform",
    version="1.0.0",
    dependencies=(),
    routers=(
        login.router,
        dashboard.router,
        users.router,
        utils.router,
        logs.router,
        roles.router,
        menus.router,
        notices.router,
        permissions.router,
        posts.router,
        departments.router,
        dictionaries.router,
        system_settings.router,
        files.router,
        sms.router,
        mail.router,
        site_messages.router,
        oauth2.router,
        social.router,
        tenants.router,
        modules.router,
    ),
    api_prefix="/api/v1/platform",
    permission_prefix="platform",
    migration=MigrationSpec(namespace="platform", schema="public"),
    event_publishers=(
        EventContract("platform.master_data.lifecycle", 1),
    ),
    workers=("outbox-dispatch",),
)
